### ISSUE TITLE
Automate boot cycle of nodes.

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#1046]
#### Detailed description

Currently when CPU node freezes, operations needs to reboot the node and rebuild the VXLan's etc ...  this should be automated

e.g https://docs.greenitglobe.com/gig/proj_gig_sweden/issues/26

**Comment by FastGeert** [comment]
Before we go to an automatic rebooting of nodes feature, we first need to understand better when and how it happens that nodes freeze.

In the meantime we definitely need to automate the boot cycle, so that no intervention of OPS is needed on the host after a reboot to make a node operational again.

**Comment by ashraffouda** [comment]
this needs more info on how this can be done

**Comment by grimpy** [comment]
NOt needed when proper procesures are used
