### ISSUE TITLE
Online upgrades  firmware-bios-code (rolling upgrade)

### ISSUE THREAD

**Issue by wvandebroeck** [0-complexity/openvcloud#1177]
**Motivation** 

When cluster upgrades need to be performed (code, patches, firmware or bios) VM’s running on the cluster cannot go down.   

Currently we have a case where firmware updates are needed in the field on all platforms due to the intel security issue.  This is a good case to automate this in OVC.

**Terminologies and Concepts** 

Related to the KVM hypervisor and storage
Nutanix: http://myvirtualcloud.net/nutanix-one-click-upgrade-now-takes-care-of-firmware-and-hypervisor-too/ 
VMware: https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.upgrade.doc_50%2FGUID-712F3F65-A2C8-4B5C-8E99-0C935CAA8C9A.html 

**Goals** 

Ensure availability of VM’s running on the cluster in case a cluster upgrade needs to be performed.

**Comment by FastGeert** [comment]
@grimpy He Jo, can you estimate the effort please.

**Comment by dinosn** [comment]
For reference, VMware ESXi is not performing any BIOS/Firmware updates on the systems. The updates on the VMware ESXi are on the hypervisor itself.

The valid reference is the one to nutanix as far as I can see only.

There are some more things to consider, BIOS/Firmware updates might require

1. System to be running without OS , eg booted from a CDrom or a PXE image ( Jan's 911 is perfect case )
2. In some cases these upgrade will require manual intervention to perform changes to new  BIOS / Firmware settings.

I believe that the new security issue that is mentioned above on the ticket, is the meltdown exploit. Mitigation for this case will not be on the BIOS / Firmware but with kernel patches.

**Comment by FastGeert** [comment]
Nevertheless, an automated update procedure that can perform tasks on a system level is something we need. Otherwise we keep fiddling on each physical node and hence introduce human errors.

**Comment by FastGeert** [comment]
@grimpy He Jo, can you estimate the effort please.

**Comment by grimpy** [comment]
@FastGeert I still dont get the full requirements here what you described is basicly why maintenance mode exist

**Comment by grimpy** [comment]
@wvandebroeck read @dinosn his reply

**Comment by wvandebroeck** [comment]
@grimpy and @dinosn Not correct http://www.yellow-bricks.com/2017/04/11/whats-new-vsan-6-6/
Do we want to keep performing manual upgrades?

**Comment by dinosn** [comment]
You are not comparing equal things here. 

  What has vsan to do with our installation and how do you believe that it's the same thing as our process?

Please get things straight, on our environment is not possible at the moment.  

Also because you read firmware upgrade how do you think that this is possible.  

Take the issue into real technical perspective, you have CUSTOM hardware that you need to perform firmware upgrade, how possible is that vmware will have a firmware that is custom, requires custom tools in most cases to be deployed. 

Please do not stay in the headlines but dig deeper this is not an issue for the moment to be handled through automation. 

To update the firmware update on the LSI controllers that we are using the process requires also manual input, yes it could be automated. 

No it's not going to be done as these products do not change firmware often.  

Automation will take a considerable amount of time on development side for something that might not required, too complex to implemented, with high dependencies on the vendor and will also need custom input/tuning depending on the tool that will be provided from the hardware vendor each time.

Today even with ESXi 6.5 vmware has no control over bios items and I can verify that by showing you how the process of upgrading a firmware on a HP BL640 G8/9 is done from a C7000 enclosure. 

ESXi and VCenter are barely aware on the hardware that they are running more to say that their upgrade will have bios and ACTUAL firmware patches.

A last note here is that any change might reset settings into BIOS that will definitely require manual change.

If you have an easy way though that I'm missing and you can suggest a tool that will unify firmware and bios upgrades I'm open to test the solution.

Thanks in advance.

**Comment by wvandebroeck** [comment]
@riaandn1 as this is a request of operations i would like you to comment on the need for this feature because it seems that @dinosn does not agree.  

I would also like to point out that Terminologies and Concepts are only to give examples how other companies are doing things I dont say we need to do the same. Personally thinking of the future if we have 10's or even 100's of G8's out in the field upgrade firmware and patches is going to be a nightmare if you keep on doing things manually.  

Besides all of the things discussed above I would also like to point out once engineering and product management agreed we need to put a feature in a certain version and gave a priority you cannot simply step in and change priorities.  If you see the need to do changes we are open to all proper feedback but not without a decent discussion.

**Comment by grimpy** [comment]
Jo is going to write some specs that need to be reviewed by @FastGeert @wvandebroeck

**Comment by riaandn1** [comment]
I agree with Wim and Geert. We need this in operations amd I would like to see this feature. All images in future for a hardware stack will be version controlled. By image I refer to the version of the OS, network drivers, kernel as well as any tunable parameters.  A good start is the specifications from Jo. From time to time there will be a need to bring an environment up to date. A good example is MA, which we could not do because it was taking to long. It does not have to happen in 2.3.1 but the sooner we can get this the better.

**Comment by dinosn** [comment]
I'm sorry but please do take some time and understand the topic. 

   We are referring to firmware and bios. It has nothing to do with with OS / Network or Kernel drivers.

**Comment by riaandn1** [comment]
I spoke to Geert and you are correct. Nonetheless we need this capability to push a button from OVC to update a node using a script.

**Comment by hofkensj** [comment]
We need a simple, OVC API Callable way to do the following:
1 - move all load from either a STOR or a CPU node
2 - execute a script on the node that might need a restart / reboot
3 - bring the node back up
4 - make the node in its old role back in production

We should be able to do this for
1 - all STOR nodes
2 - all CPU nodes
3 - a specific STOR node
4 - a specific CPU node

What needs to be done for the controllers ? do we need a similar function ?

**Comment by ahmedelsayed-93** [comment]
it needs a green environment to be tests
