### ISSUE TITLE
When an orphan disk that has clones gets deleted it crashes the entire orphan

### ISSUE THREAD

**Issue by grimpy** [0-complexity/openvcloud#1205]
#### Detailed description
When there is a disk that has clones gets in orphan orhpan checks fails to remove it and crashes. it does not even bother to continue with the other disks.

#### Steps to reproduce

Have an orphan disk for 7days which has a clone

**Comment by Dinaamagdy** [comment]
## Software Version 
```
JumpScale
Core: branch: master (0de3a2b) 3/4/2018, 2:06:10 PM
Portal: branch: master (3bb6e8e) 3/4/2018, 6:44:27 PM
OpenvCloud
Core: branch: master (7e570f3) 3/4/2018, 8:49:52 PM
G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: branch: master (4adf360) 3/4/2018, 10:58:12 AM
```

**Comment by Dinaamagdy** [comment]
## Verification steps 
- Create vdisk from storage portal .
-  Run the following  script at any storage node 
/opt/jumpscale7/apps/processmanager/jumpscripts/healthchecks/disk_orphan.py  
with option -d 1 
- after script finish , check that your vdisk deleted

**Comment by dinosn** [comment]
Hello, 

  I'm reopening this as this is not resolved. 

When a disk is cloned it cannot be deleted unless the -clone is also removed, as the parent contains all actual data.

This is the case that is preventing cloud-init-vm-8169 of vm-8169 on Red Centric env to be removed. 

The issue was initially reported to OVS under http://support.openvstorage.com/servicedesk/customer/portal/1/OVSSUP-465 but it's not actually an OVS issue. 

We should check if there are cloned images and either move the data from the parent node to the clone ( replace it ) or display a proper message for this to be handled differently.

**Comment by ashraffouda** [comment]
@dinosn are u talking generally about deleting disks that have clones?
cause the orginal issue is about the disk-orphanage healthcheck

**Comment by dinosn** [comment]
Hi the issue appeared initially as disk orphanage that was persistent for days

**Comment by ashraffouda** [comment]
https://github.com/0-complexity/selfhealing/pull/189

**Comment by katia-e** [comment]
Error in job `diskdelete` when deleting disk that has clones:
https://be-g8-3.demo.greenitglobe.com/grid/job?id=69ae4ed52c784d04bc03c80730d2d76e

Error condition:
https://be-g8-3.demo.greenitglobe.com/grid/error%20condition?id=31e81aeb-520c-1fd4-466d-d025800d0d97
