### ISSUE TITLE
LimitIO for Disk errors vaguely for negative value

### ISSUE THREAD

**Issue by katia-e** [0-complexity/openvcloud#1522]
#### Detailed description
During the tests limiting IO for disk with negative value threw an error, but anyway appeared in the disk info.

#### Steps to reproduce
``` python
ovc_se = j.clients.openvcloud.get('se')
acc = ovc_se.account_get(name='Katja', create=False) 
ovc_se.api.cloudapi.disks.limitIO(diskId=3248,size_iops_sec=-1)
```
The error follows, but value still gets updated on `account.disks`:
![image](https://user-images.githubusercontent.com/32639869/38814721-7d7343b8-4192-11e8-9bed-9fc51b06b75d.png)

**Comment by chrisvdg** [comment]
https://github.com/0-complexity/openvcloud/blob/master/apps/cloudbroker/base/cloudapi__disks/methodclass/cloudapi_disks.py#L99
Doesn't look like the `size_iops_sec` argument is actually used

**Comment by chrisvdg** [comment]
So the `iotune` variable is passed to the limitdiskio jumpscript (https://github.com/0-complexity/openvcloud/blob/master/libs/agent-scripts/libvirt/limitdiskio.py#L36) and is used there to create a `virsh` command. For this whole trip. there is no validation for the `size_iops_sec` argument. 
I'd guess this command fails because of the negative value and the `libvirt_driver` abstracted this error (https://github.com/0-complexity/openvcloud/blob/master/libs/CloudscalerLibcloud/CloudscalerLibcloud/compute/drivers/libvirt_driver.py#L343)

So either we need to make sure the original error is also retrieved/parsed/checked/... to make the error message more clear or add validation for the parameters to the `limitIO` method.

**Comment by katia-e** [comment]
Cannot verify right now, trying to limit disks on be-g8-3 produce error condition
https://be-g8-3.demo.greenitglobe.com/grid/error%20condition?id=7921a20d-1932-620b-d452-ab9d5bc0c566
