### ISSUE TITLE
Generated reports from Resource Consumption Tracking does not work properly 

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1557]
#### Detailed description
i have follow the procedure of Resource Consumption Tracking as https://github.com/0-complexity/openvcloud/blob/master/docs/Monitoring/ResourceTracking/README.md
No data exist (zero) on the generated excel file as attached picture and the account is production!

#### Steps to reproduce
Run the  Resource Consumption Tracking on be-gen-1 as mentioned on above repo

#### Installation information
```
    Core: branch: production (a5c4eee) 2/14/2018, 1:32:38 PM
    G8VDC: tag: v2.2.6 (989668b) 12/27/2017, 4:19:04 PM
    Selfhealing: branch: production (3bc2f9b) 2/7/2018, 1:58:11 PM
```

**Comment by Pishoy** [comment]
![ovc](https://user-images.githubusercontent.com/21987477/40105008-0db90036-58f2-11e8-8ed5-6ca0ab6f90ab.jpg)

**Comment by Pishoy** [comment]
https://docs.greenitglobe.com/gig/org_support/issues/567

**Comment by Pishoy** [comment]
any update ?

**Comment by FastGeert** [comment]
@grimpy please document the whole flow of information.

**Comment by katia-e** [comment]
Might have been broken by this [commit](https://github.com/0-complexity/openvcloud/pull/1564/commits)

**Comment by katia-e** [comment]
Current state:

since update of be-g8-3 7/10/2018 resmonitoring job isn't scheduled on agentcontroller.
Period of the task is set to `period = "0 * * * *"`, presumably it means every hour, however, job doesn't appear in the logs lately. Logs of agentcotroller don't show any errors in API responses.
(logs I was checking here `kubectl logs agentcontroller-5bc6767c54-hspl7 --container agentcontroller-container`)

Scheduling job manually result in timeout. 

![screenshot from 2018-07-13 10-44-24](https://user-images.githubusercontent.com/32639869/42682066-c74aa710-8689-11e8-9af3-4417cbd135ee.png)

**Comment by chrisvdg** [comment]
Confirmed resources are being collected
![image](https://user-images.githubusercontent.com/23582741/43469684-07576a08-94e7-11e8-948a-98a3836639e6.png)
