### ISSUE TITLE
bug - adding pub key to IYO profile is compulsory for "normal users"

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#1568]
#### Detailed description

When a new users is invited to the "user" org of an environment, they need to give their public key as a compulsory information.  

This is not technically needed - so should not be compulsory

![image](https://user-images.githubusercontent.com/16613288/41165893-137faf88-6b3f-11e8-9d7e-a60d3136fc1b.png)

**Comment by FastGeert** [comment]
Is this a required or optional attribute?

**Comment by ahmedelsayed-93** [comment]
According to @LeeSmet 
currently, optional scopes is not supported in itsyou.online

**Comment by FastGeert** [comment]
@hofkensj what if we turn this around, and automaticaly proviosion the users ssh key into the created vm's via cloudinit to increase the value of the sshkey in the users IYO profile?

**Comment by FastGeert** [comment]
After some discussion we decided that we will not ask the ssh scope for people logging in to the enduser portal. Logging in on the admin portal will still require the ssh key scope

**Comment by katia-e** [comment]
@ahmedelsayed-93, something else to investigate

after update on 26.07 I tried to login via user portal **failed**, while login via admin portal was successful.
By "failed" I mean that `itsyouonline` credentials were requested but then portal went back to the page before, instead of proceeding to the list of vdc's.
