### ISSUE TITLE
"Swap used value" is causing red alarms all over the store nodes with no actual reason.

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#842]
The "Swap used value is" reported on the store nodes mainly is causing the system to have permanent red status. 

It's a condition that we cannot avoid and a condition that it's not critical. 

As we don't have control to acknowledge an alarm please set the thresholds to values much higher
<img width="1394" alt="screen shot 2017-04-07 at 10 52 29" src="https://cloud.githubusercontent.com/assets/3851678/24790797/6095ba48-1b80-11e7-9291-8b704d7d1e18.png">
The image is from the mauritius production environment.

**Comment by islamTaha12** [comment]
run the following comment
```
stress-ng --vm-method rowhammer -r 500
```
**result**
It looks like that for since 10 mins

![image](https://user-images.githubusercontent.com/17981089/34202563-bd28a624-e580-11e7-8815-3c3a3b1bd0d9.png)

![image](https://user-images.githubusercontent.com/17981089/34202625-fcbc1578-e580-11e7-93ef-40de015a15f6.png)


**System version**
JumpScale

Core: branch: master (bdbb2fd) 12/19/2017, 10:14:55 AM
Portal: branch: master (9a65ce8) 12/19/2017, 10:56:59 AM
OpenvCloud

Core: branch: master (bfea912) 12/19/2017, 6:45:57 PM
G8VDC: branch: master (2f5e95f) 12/19/2017, 8:37:17 AM
Selfhealing: branch: master (0893c28) 12/19/2017, 11:34:51 AM
OpenvStorage be-g8-3

openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1

**Comment by ashraffouda** [comment]
from what I see in the script, 
we only report the warning or error status in the amount of used mem(actual memory) not the swap exceeded **80%** in the **last hour**
so if the used swap turns 90% no errors will be reported
the health check results in the screen shot shows **0%** used mem in the last hour, because all stats r the stats from last hour, so it is normal that the swap is in ok status 
https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/swap_used_check.py#L54
is this something that we need to remove ? and we do check for the swap regardless the mem values?

**Comment by FastGeert** [comment]
Looking at the code, I think it makes sense, and there is no need for further improvements.

**Comment by john-kheir** [comment]
I see here 2  problems:
1- The average memory load is 0.00% which doesn't make sense to me
 - Also concerning this script: https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/swap_used_check.py#L54, i have a question: Are The average memory value and the swap calculated at the same moment? because if so then there should be a problem in our calculations because the memory should be full
2- If the average memory is collected every hour and the swap every 5 mins (not sure if that's right), i feel that's a big time difference which is one reason for this issue.

**Comment by FastGeert** [comment]
All stats are collected every 5 minutes.

Need to check 0.00% mem load

**Comment by ashraffouda** [comment]
found an issue in mem calculations, we r using the available not the used, fixed and testing it now

**Comment by ashraffouda** [comment]
https://github.com/0-complexity/selfhealing/commit/ddb3754fcb12b6e0ac396548c4659bfa1e6d07d7
https://github.com/0-complexity/selfhealing/commit/2ee8c28bb1df3deb6870080fd90a1b0aba8e0305
